# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
# Recommended: set this to a particular "release" of Open SDG. For example:
remote_theme: open-sdg/open-sdg@1.1.0

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/sdg-site-bristol"
url: ""
data_dir: data
environment: staging

# In the next few items, replace "open-sdg" with the name of your GitHub
# organization, and "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "https://sdg-bristol.github.io/sdg-data-bristol"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#sdg-bristol/sdg-data-bristol/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#sdg-bristol/sdg-data-bristol/edit/develop/meta/[id].md

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
create_pages: true

analytics:
  ga_prod: ''

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: city.office@bristol.gov.uk 
  suggestions: city.office@bristol.gov.uk 
  functional: city.office@bristol.gov.uk 

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Bristol
  adjective: Bristol

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
#frontpage_instructions: Click on each goal, or <span id="jump-to-search"><a>search</a></span>, for Australian statistics for Sustainable Development Goal global indicators.

# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

footer_menu:
  - path: mailto:city.office@bristol.gov.uk 
    translation_key: menu.contact_us
  - path: https://twitter.com/BristolOneCity 
    translation_key: general.twitter
  - path: https://www.bristolonecity.com/sdgs/  
    translation_key: SDGs - Bristol One City
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies

# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/translations-un-sdg/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
