# Jekyll configuration for Open SDG platform

# Tell the Remote Theme plugin to use the Open SDG platform (Jekyll theme).
# Recommended: set this to a particular "release" of Open SDG. For example:
remote_theme: open-sdg/open-sdg@1.5.0

# Replace this title as needed.
title: Indicators For The Sustainable Development Goals
# Replace the baseurl with the name of this repository.
baseurl: "/sdg-site-bristol"
url: ""
data_dir: data
environment: staging

# Accessibility options
# This setting can be set to true to enable tab functionality that is 
# compliant with the WAI-ARIA best practices. This adds improved keyboard navigation of the tabs. 
# This defaults to false, however setting this to true is recommended.
accessible_tabs: true
# This setting can be set to true to enable chart functionality that is
# intended to increase accessibility by adding support for screenreaders and keyboard navigation.
# This defaults to false, however setting this to true is recommended.
accessible_charts: true
# Graph colour set
# Recommended is accessible
graph_color_set: accessible
# Contrast type controls the selector for high contrast.
# default: Two buttons containing "A" - one for on and one for off (this is the default if you omit this setting)
# long: If you use this option one single button will be displayed with the text 'High contrast' / 'Default contrast', depending on which mode of contrast is active.
# single: One button containing "A" which toggles on/off, depending on which mode of contrast is active. This is recommended for the cleanest display.
contrast_type: single

# In the next few items, replace "open-sdg" with the name of your GitHub
# organization, and "open-sdg-data-starter" with the name of your data repository.
remote_data_prefix: "https://sdg-bristol.github.io/sdg-data-bristol"
# URL for the "Edit Data" button on indicators.
data_edit_url: http://prose.io/#sdg-bristol/sdg-data-bristol/edit/develop/data/indicator_[id].csv
# URL for the "Edit Metadata" button on indicators.
metadata_edit_url: http://prose.io/#sdg-bristol/sdg-data-bristol/edit/develop/csv-meta/[id].csv

# Automatically create indicator pages, goal pages,
# and some other required pages.
create_indicators:
  layout: indicator
create_goals:
  layout: goal-by-target
create_pages: true

analytics:
  ga_prod: ''

# Sticky share buttons (facebook, twitter and email)
#sharethis_property: '5d279253faeee40012f195e1'

# Replace the email addresses below.
email_contacts:
  questions: city.office@bristol.gov.uk 
  suggestions: city.office@bristol.gov.uk 
  functional: city.office@bristol.gov.uk 

# International Support
# Eg name: Australia and adjective: Australian
country:
  name: Bristol
  adjective: Bristol

# Optionally uncomment and update the settings below to control the frontpage heading and instructions.
#frontpage_heading: Australian data for Sustainable Development Goal indicators
frontpage_instructions: Click on each goal, or <span id="jump-to-search"><a>search</a></span>, for Bristol statistics for Sustainable Development Goal global indicators.

# header can be used to specify new of old style header
header:
   include: header-menu-left-aligned.html
# Pages
collections:
  pages:
    output: true
    permalink: /:path/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title.html
  indicators:
    output: true
  goals:
    output: true

# Menu
menu:
  # Use these to customise the main navigation.
  - path: /reporting-status
    # The "translation_key" refers to the key in the SDG Translations repository.
    translation_key: menu.reporting_status
  - path: /about
    translation_key: menu.about
  - path: /guidance
    translation_key: menu.guidance
  - path: /faq
    translation_key: menu.faq

footer_menu:
  - path: mailto:city.office@bristol.gov.uk 
    translation_key: menu.contact_us
  - path: https://twitter.com/BristolOneCity 
    translation_key: general.twitter
  - path: https://www.bristolonecity.com/sdgs/  
    translation_key: SDGs - Bristol One City
  - path: /about/cookies-and-privacy/
    translation_key: menu.cookies


map_options:
  # Control the limits on zooming in/out in the map:
  # If you would like to use tile (background) imagery, use these:
 tileURL: https://{s}.tile.jawg.io/{id}/{z}/{x}/{y}{r}.png?access-token={accessToken}
  tileOptions:
    id: jawg-light
    accessToken: 6D21hTioQUEfcuV4EEEg1UH4W98hoHu4k832Jdod3KqX9DMM2yClAkc8Zfs7XPKg
    attribution:  <a href="http://jawg.io" title="Tiles Courtesy of Jawg Maps" target="_blank">&copy; <b>Jawg</b>Maps</a> &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors | <a href="http://geoportal.statistics.gov.uk/">ONS</a>
  minZoom: 4
  maxZoom: 16
  # Control the choropleth color range. See https://gka.github.io/chroma.js/#chroma-brewer
  colorRange: chroma.brewer.BuGn
  # Set the color for boundaries that have no data.
  noValueColor: #f0f0f0
  # For documentation on the style options below, see here:
  # https://leafletjs.com/reference-1.4.0.html#path-option
  # Set the default style for boundaries in the map:
  styleNormal:
    weight: 1
    opacity: 1
    color: #888888
    fillOpacity: 0.7
  # Set the style for boundaries that have been selected/highlighted:
  styleHighlighted:
    weight: 1
    opacity: 1
    color: #111111
    fillOpacity: 0.7
  # Set the style for top-level boundaries that are displaying in other layers.
  # Note: This is only applicable when using the "nested zoom" feature (see below).
  styleStatic:
    weight: 2
    opacity: 1
    fillOpacity: 0
    color: #172d44
    dashArray: 5,5

map_layers:
  - min_zoom: 4
    max_zoom: 6
    staticBorders: true
    subfolder: country
    label: Country
  - min_zoom: 6
    max_zoom: 8
    staticBorders: true
    subfolder: regions
    label: Regions
  - min_zoom: 9
    max_zoom: 12
    staticBorders: true
    subfolder: local_authorities
    label: Local Authorities
  - min_zoom: 12
    max_zoom: 16
    staticBorders: true
    subfolder: wards
    label: Wards


# Configure the text (or "translation key") to be used on the
# non-global metadata tab.
non_global_metadata: indicator.national_metadata

# The list of languages that are translated. The first one is the default.
languages:
  - en

# Set a base for all goal image URLs. Note that the full goal image path will be
# the base below, completed with: /[language]/[number].png (eg, /fr/6.png).
goal_image_base: https://open-sdg.github.io/translations-un-sdg/assets/img/goals

# Tell Jekyll to use the Remote Theme plugin.
plugins:
  - jekyll-remote-theme
  - jekyll-open-sdg-plugins
